### ISSUE TITLE
Course 6 Backcompatibility

### ISSUE THREAD

**Issue by mariemusic** [sipb/hydrant#1]
Course 6 classes have no hours or ratings presumably bc of the lack of official links between old and new numbers. This makes questions like "how many hours should this schedule actually take" unanswerable by Hydrant at the moment, which is one of the main ways I used to use Firehose. Presumably doing this linking inside Hydrant is reasonable to do since it exists for Fall 22. Thanks!

![image](https://user-images.githubusercontent.com/45956192/205341679-5d45cfc5-3d7c-42df-ba70-671d2d8e06f4.png)

**Comment by psvenk** [comment]
This should be resolved once <https://github.com/venkatesh-sivaraman/fireroad-server/pull/40> is merged.

**Comment by cjquines** [comment]
still blocked on fireroad server doing things right?

**Comment by psvenk** [comment]
Will investigate and update.

**Comment by psvenk** [comment]
Yes, this is still blocked on getting access to the FireRoad server. The necessary changes have been made in the FireRoad codebase and it works properly on a local instance of FireRoad.

**Comment by psvenk** [comment]
This has now been resolved.
