### ISSUE TITLE
Courses offered both half-terms

### ISSUE THREAD

**Issue by Lily2Sen** [sipb/hydrant#15]
In catalog.py, the function get_half only returns 1 or 2 for whether it's first half or second half, but there are some courses that are offered in both. I would just fix the function itself but not sure whether it will cause issues later on.

Wait I may have spoken too soon, let me run a couple tests sorry.

**Comment by cjquines** [comment]
it would return `False` for courses in both?

**Comment by Lily2Sen** [comment]
I meant courses that are a quarter length, but offered in both the first and the second half of the semester (offered twice in one semester). I believe this would return just 1 in that case. However, just looking at the subject listing, they technically use different course numbers for the course offered in the first vs in the second. I'm running a test now to make sure that's true for all of them, but my computer is very slow lol.

**Comment by Lily2Sen** [comment]
Confirmed that there aren't any courses currently. Sorry about that. It might be something to look into in the future though.
