### ISSUE TITLE
Course 6 is kinda missing

### ISSUE THREAD

**Issue by wilke0818** [sipb/hydrant#21]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/39885245/215572544-b063425f-47aa-4714-924a-c39367d864ee.png">
These are the only classes for all of couse 6

**Comment by cjquines** [comment]
This is a known issue due to Course 6 classes having disappeared from
the course catalog; it should be fixed soon whenever the course catalog
is fixed (unfortunately, there's nothing that we can do about it).
