### ISSUE TITLE
MIT site currently broken

### ISSUE THREAD

**Issue by dannys4** [sipb/hydrant#23]
Sometime between 2/3 and 2/5 it seems the site hydrant.mit.edu went down and now displays a 403. As a stopgap, the [wayback machine](https://web.archive.org/web/20230203062838/https://hydrant.mit.edu/) has a usable version from 2/3 haha (EDIT: it doesn't allow any calendar exports though). If I had to guess, it would be from a botched crontab deployment after the recent PR, but I can't really be sure. Thanks for all the hard and often thankless work!

**Comment by cjquines** [comment]
no, it's down because scripts is down. there's a mirror up at https://sipb.github.io/hydrant/
