### ISSUE TITLE
ics export should be timezone-aware

### ISSUE THREAD

**Issue by cjquines** [sipb/hydrant#26]
@dolphingarlic

**Comment by cjquines** [comment]
gonna bump this, it's gonna come up soon and we're going to get a bunch of complaints. @SuperC03

**Comment by cjquines** [comment]
i can still repro this; i think the problem is that it exports events in UTC rather than eastern

**Comment by cjquines** [comment]
we got another email about this so i am escalating again, @psvenk can you assign someone to investigate?

**Comment by psvenk** [comment]
> we got another email about this so i am escalating again, @psvenk can you assign someone to investigate?

I investigated a bit earlier today and couldn't pin down what was going wrong. (The specific scenario from the person who emailed seems like it shouldn't happen if we're exporting with the correct absolute time in UTC, but I haven't tried reproducing on a machine set to a non-ET time zone; I am aware, OTOH, of the DST issue.) I'll look at it some more and/or assign someone in the next few days.
