### ISSUE TITLE
Not offered tooltip has the wrong academic year

### ISSUE THREAD

**Issue by gabrc52** [sipb/hydrant#44]
![image](https://github.com/sipb/hydrant/assets/24363938/6f077825-e8a2-4dbc-bbe8-173762be2ae1)

Compare to the tooltip in the course catalog:

![image](https://github.com/sipb/hydrant/assets/24363938/3048aabb-5cc2-4881-b1c2-98637c113941)

**Comment by cjquines** [comment]
oh lol we hardcode it https://github.com/sipb/hydrant/blob/a07ebcd99427cfd9356d83092cd8932313757f60/src/components/ActivityDescription.tsx#L63

**Comment by cjquines** [comment]
(the fix is to probably use `state.term` to get the academic year)
