### ISSUE TITLE
Allow custom locations for classes

### ISSUE THREAD

**Issue by SuperSonicHub1** [sipb/hydrant#46]
Building on top of #12 and #43, classes should also allow having custom locations. Lectures, recitations, and labs should all be independently editable.

This is useful for classes whose actual meeting locations don't reflect the ones in the course catalog (e.g. 21M.470) or classes whose locations change in the middle of a semester (e.g. my 18.01 lecture :')).

**Comment by cjquines** [comment]
will need a bit of design, but we can steal part of it from #43 (thanks @kierajreed !)

**Comment by kierajreed** [comment]
Oh hey Kyle! Fancy seeing you here. I think stealing the location code from activities would work nicely, but the UI could be changed (putting "override location" in the section selection menus would look nice imo).
