### ISSUE TITLE
write better onboarding documentation

### ISSUE THREAD

**Issue by cjquines** [sipb/hydrant#49]
the "local development" section of "updating" should be more explicit about how to do local development. i mean, right now we say "Make sure to update the backend before you run the frontend for the first time", this should be turned to a step by step 1. update the backend, 2. run npm start, 3. make changes they will appear live

**Comment by psvenk** [comment]
This just bit me at the SIPB hackathon today!

**Comment by cjquines** [comment]
btcywtsitw
