### ISSUE TITLE
Set up a linter (with CI?) for the backend/frontend

### ISSUE THREAD

**Issue by Alwinfy** [sipb/hydrant#54]
Probably want to use [ESLint](https://eslint.org/) and [Prettier](https://prettier.io/) for the frontend and something like [Black](https://github.com/psf/black) for the backend.

Note: Do **not** try to use ESLint's `indent` directly, it's busted! See [here](https://github.com/typescript-eslint/typescript-eslint/issues/1824).

**Comment by Haile-08** [comment]
can work on this issue
