### ISSUE TITLE
Hydrant hangs when loading IAP 2024 classes

### ISSUE THREAD

**Issue by carreter** [sipb/hydrant#64]
## The issue
Hydrant will hang when attempting to load IAP 2024 classes due to a 404 for the schedule data.

## Steps to replicate:
Go to https://hydrant.mit.edu/?t=i24 or click on "IAP 2024" in the semester dropdown.

## Screenshot:
![image](https://github.com/sipb/hydrant/assets/5355463/b002436c-73e1-457f-8662-1e9e5a44e041)

**Comment by psvenk** [comment]
Thanks for opening this issue; this happens because #7 has not yet been resolved (so IAP is not distinguished from spring). I'll try to work on this soon. In the meantime, I have hidden IAP 2024 from the dropdown just as IAP 2023 is hidden.
