### ISSUE TITLE
Potential bug report - Incorrect 6.390 schedule info

### ISSUE THREAD

**Issue by shensquared** [sipb/hydrant#65]
Hi, 

I'm teaching [6.3900[6.036] Intro to Machine Learning](https://introml.mit.edu/spring24)  in Spring24. I'm writing to report a schedule issue on Hydrant for the class.

We traditionally have Monday/Wednesday class meetings. These are correctly scraped to Hydrant. 

We added a Friday class meeting in Spring24, and it was updated on the Registrar http://student.mit.edu/catalog/m6c.html#6.3900 on Jan 2. This update isn't reflected on Hydrant. 

I poked around the repo a bit and my understanding is https://github.com/sipb/hydrant/tree/deploy/public has all the raw data but it's not updated for a while. So this seems to be a delayed scraping issue to me? (but then hydrant site shows Last updated: 2024-01-25 13:00 right now, so I'm not sure).

Would appreciate any pointers? Happy to help debug/fix too. Thanks.

**Comment by cjquines** [comment]
seems there to me 
![image](https://github.com/sipb/hydrant/assets/3197784/69f77406-d841-4b70-b6df-2cf2ef12f1ec)

**Comment by cjquines** [comment]
perhaps you're looking at fall 2023?

**Comment by shensquared** [comment]
Thanks CJ. Indeed, I refreshed and do the Friday class now. Great!

Curious though. I don't think I was looking at f23 (checked my browsing history, and the URL is the baseURL, doesn't have `\?t=f23`). I wish I'd thought of taking a screenshot.

I'll see if I can find out more to help understand the issue (or the non-issue 😉) Thanks again.

**Comment by cjquines** [comment]
the "Last updated: 2024-01-25 13:00" thing is directly linked to the data that it shows; `latest.json` has a key called last updated or something

it's possible that the fireroad data wasn't updated—i'm not sure how often the fireroad backend gets updated, @psvenk ?

**Comment by psvenk** [comment]
Yes, the FireRoad server is still updated manually by running a script; I still need to look into automating it. (And to answer your earlier question, `latest.json` is deliberately not tracked in this respository because it is updated from the FireRoad server periodically by a cron job; previous terms, OTOH, are frozen.)

**Comment by psvenk** [comment]
By the way, I updated FireRoad and Hydrant earlier today. Let us know if you're still facing issues.

As for what was happening before, it's possible that your browser had cached an older version of the `latest.json` file; I'm not sure what the TTL for that is on Scripts (where Hydrant is hosted).

**Comment by cjquines** [comment]
for what was happening before, note that, again, the "Last updated: 2024-01-25 13:00" thing is directly linked to `latest.json`, so whatever hydrant shows under last updated is guaranteed to be when the loaded `latest.json` was last updated

**Comment by cjquines** [comment]
(closing as cannot repro)
