### ISSUE TITLE
fireroad.py can't parse schedule for 15.089?

### ISSUE THREAD

**Issue by duck-master** [sipb/hydrant#79]
When I run `python3 update.py` on a freshly cloned copy of this repo, I get the following message as part of the output:

```
=== Update fireroad data ===
Can't parse schedule 15.089: '11'
Got 1923 courses
Skipped 4735 courses due to missing schedules
```

**Comment by psvenk** [comment]
Hmm, it seems that the schedule parsing code on the FireRoad backend has an issue with "M8-5,T11-2,W EVE (11-6 PM)". I'll take a look in the next few days unless someone else does.
