### ISSUE TITLE
npm start / npm build don't type check

### ISSUE THREAD

**Issue by psvenk** [sipb/hydrant#89]
It turns out that Create React App's `npm start` and `npm build` don't check if the source type checks; they just run Babel and throw an error if the input is not syntactically valid TypeScript. We should run `tsc` somewhere (both for these scripts and for CI) instead of just relying on editor integrations and/or manually running `tsc`.

**Comment by cjquines** [comment]
i've basically never seen a project where the `npm` dev command runs typechecking or linting.

the build command i've sometimes seen runs the lint and typecheck
