### ISSUE TITLE
Add prereg button

### ISSUE THREAD

**Issue by dtemkin1** [sipb/hydrant#97]
You can specify what subjects to add prefilled to your prereg using a URL search query (eg. https://student.mit.edu/cgi-bin/sfprwtrm.sh?6.1020,11.001 would add 6.1020 and 11.001 to your preregistration). Maybe adding a button to add all the classes in your schedule to your prereg would be nice

**Comment by gabrc52** [comment]
That's incredible, I didn't know student.mit.edu had that feature. The implementation could look very similar to the matrix class chats button since it also constructs a URL.

**Comment by dtemkin1** [comment]
Maybe we can move the "maintained by SIPB" to somewhere in the header and place a "prereg here" button there?

**Comment by cjquines** [comment]
wait this is such an awesome feature
